import { Product, Category } from '@/types/product';

export const dummyCategories: Category[] = [
  {
    id: 1,
    name: 'Elektronik',
    slug: 'elektronik',
    parent: 0,
    description: 'Moderne Elektronikgeräte und Gadgets für den Alltag',
    display: 'default',
    image: {
      id: 101,
      date_created: '2024-01-15T10:00:00',
      date_modified: '2024-01-15T10:00:00',
      src: 'https://images.unsplash.com/photo-1498049794561-7780e7231661?w=500&h=500&fit=crop',
      name: 'elektronik-kategorie',
      alt: 'Elektronik Kategorie'
    },
    menu_order: 1,
    count: 3
  },
  {
    id: 2,
    name: 'Mode & Accessoires',
    slug: 'mode-accessoires',
    parent: 0,
    description: 'Stylische Kleidung und Accessoires für jeden Anlass',
    display: 'default',
    image: {
      id: 102,
      date_created: '2024-01-15T10:00:00',
      date_modified: '2024-01-15T10:00:00',
      src: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=500&h=500&fit=crop',
      name: 'mode-kategorie',
      alt: 'Mode Kategorie'
    },
    menu_order: 2,
    count: 2
  },
  {
    id: 3,
    name: 'Wohnen & Deko',
    slug: 'wohnen-deko',
    parent: 0,
    description: 'Schöne Wohnaccessoires und Dekoration für Ihr Zuhause',
    display: 'default',
    image: {
      id: 103,
      date_created: '2024-01-15T10:00:00',
      date_modified: '2024-01-15T10:00:00',
      src: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=500&h=500&fit=crop',
      name: 'wohnen-kategorie',
      alt: 'Wohnen Kategorie'
    },
    menu_order: 3,
    count: 1
  }
];

export const dummyProducts: Product[] = [
  {
    id: 1,
    name: 'Bluetooth Kopfhörer Premium',
    slug: 'bluetooth-kopfhoerer-premium',
    permalink: '/products/bluetooth-kopfhoerer-premium',
    date_created: '2024-01-15T10:00:00',
    date_modified: '2024-01-15T10:00:00',
    type: 'simple',
    status: 'publish',
    featured: true,
    catalog_visibility: 'visible',
    description: '<p>Hochwertige Bluetooth-Kopfhörer mit erstklassiger Klangqualität und aktiver Geräuschunterdrückung. Perfekt für Musik, Anrufe und Gaming.</p>',
    short_description: 'Premium Bluetooth-Kopfhörer mit ANC',
    sku: 'BT-HEADPHONES-001',
    price: '149.99',
    regular_price: '179.99',
    sale_price: '149.99',
    date_on_sale_from: '2024-01-01T00:00:00',
    date_on_sale_to: '2024-12-31T23:59:59',
    price_html: '<span class="price"><del>179,99€</del> <ins>149,99€</ins></span>',
    on_sale: true,
    purchasable: true,
    total_sales: 127,
    virtual: false,
    downloadable: false,
    external_url: '',
    button_text: '',
    tax_status: 'taxable',
    tax_class: '',
    manage_stock: true,
    stock_quantity: 25,
    stock_status: 'instock',
    backorders: 'no',
    backorders_allowed: false,
    backordered: false,
    low_stock_amount: 5,
    sold_individually: false,
    weight: '0.3',
    dimensions: { length: '20', width: '18', height: '8' },
    shipping_required: true,
    shipping_taxable: true,
    shipping_class: '',
    shipping_class_id: 0,
    reviews_allowed: true,
    average_rating: '4.6',
    rating_count: 23,
    related_ids: [2, 3],
    upsell_ids: [],
    cross_sell_ids: [4],
    parent_id: 0,
    purchase_note: '',
    categories: [{ id: 1, name: 'Elektronik', slug: 'elektronik' }],
    tags: [],
    images: [
      {
        id: 201,
        date_created: '2024-01-15T10:00:00',
        date_modified: '2024-01-15T10:00:00',
        src: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&h=600&fit=crop',
        name: 'bluetooth-kopfhoerer-1',
        alt: 'Bluetooth Kopfhörer Premium'
      }
    ],
    attributes: [],
    default_attributes: [],
    variations: [],
    grouped_products: [],
    menu_order: 0
  },
  {
    id: 2,
    name: 'Smartphone Hülle Leder',
    slug: 'smartphone-huelle-leder',
    permalink: '/products/smartphone-huelle-leder',
    date_created: '2024-01-15T11:00:00',
    date_modified: '2024-01-15T11:00:00',
    type: 'simple',
    status: 'publish',
    featured: false,
    catalog_visibility: 'visible',
    description: '<p>Elegante Lederhülle für Smartphones mit Kartenfächern und Magnetverschluss. Bietet optimalen Schutz und stilvollen Look.</p>',
    short_description: 'Elegante Lederhülle mit Kartenfächern',
    sku: 'PHONE-CASE-LEATHER-001',
    price: '29.99',
    regular_price: '29.99',
    sale_price: '',
    date_on_sale_from: null,
    date_on_sale_to: null,
    price_html: '<span class="price">29,99€</span>',
    on_sale: false,
    purchasable: true,
    total_sales: 89,
    virtual: false,
    downloadable: false,
    external_url: '',
    button_text: '',
    tax_status: 'taxable',
    tax_class: '',
    manage_stock: true,
    stock_quantity: 50,
    stock_status: 'instock',
    backorders: 'no',
    backorders_allowed: false,
    backordered: false,
    low_stock_amount: 10,
    sold_individually: false,
    weight: '0.1',
    dimensions: { length: '16', width: '8', height: '2' },
    shipping_required: true,
    shipping_taxable: true,
    shipping_class: '',
    shipping_class_id: 0,
    reviews_allowed: true,
    average_rating: '4.3',
    rating_count: 17,
    related_ids: [1, 3],
    upsell_ids: [],
    cross_sell_ids: [],
    parent_id: 0,
    purchase_note: '',
    categories: [{ id: 1, name: 'Elektronik', slug: 'elektronik' }],
    tags: [],
    images: [
      {
        id: 202,
        date_created: '2024-01-15T11:00:00',
        date_modified: '2024-01-15T11:00:00',
        src: 'https://images.unsplash.com/photo-1601972602237-8c79241e468b?w=600&h=600&fit=crop',
        name: 'smartphone-huelle-leder',
        alt: 'Smartphone Hülle Leder'
      }
    ],
    attributes: [],
    default_attributes: [],
    variations: [],
    grouped_products: [],
    menu_order: 0
  },
  {
    id: 3,
    name: 'Wireless Ladegerät',
    slug: 'wireless-ladegeraet',
    permalink: '/products/wireless-ladegeraet',
    date_created: '2024-01-15T12:00:00',
    date_modified: '2024-01-15T12:00:00',
    type: 'simple',
    status: 'publish',
    featured: false,
    catalog_visibility: 'visible',
    description: '<p>Kabelloses Ladegerät mit 15W Fast-Charging für alle Qi-fähigen Geräte. Kompaktes Design mit LED-Statusanzeige.</p>',
    short_description: 'Kabelloses 15W Fast-Charging Ladegerät',
    sku: 'WIRELESS-CHARGER-001',
    price: '39.99',
    regular_price: '39.99',
    sale_price: '',
    date_on_sale_from: null,
    date_on_sale_to: null,
    price_html: '<span class="price">39,99€</span>',
    on_sale: false,
    purchasable: true,
    total_sales: 156,
    virtual: false,
    downloadable: false,
    external_url: '',
    button_text: '',
    tax_status: 'taxable',
    tax_class: '',
    manage_stock: true,
    stock_quantity: 35,
    stock_status: 'instock',
    backorders: 'no',
    backorders_allowed: false,
    backordered: false,
    low_stock_amount: 5,
    sold_individually: false,
    weight: '0.2',
    dimensions: { length: '10', width: '10', height: '1' },
    shipping_required: true,
    shipping_taxable: true,
    shipping_class: '',
    shipping_class_id: 0,
    reviews_allowed: true,
    average_rating: '4.5',
    rating_count: 31,
    related_ids: [1, 2],
    upsell_ids: [],
    cross_sell_ids: [],
    parent_id: 0,
    purchase_note: '',
    categories: [{ id: 1, name: 'Elektronik', slug: 'elektronik' }],
    tags: [],
    images: [
      {
        id: 203,
        date_created: '2024-01-15T12:00:00',
        date_modified: '2024-01-15T12:00:00',
        src: 'https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=600&h=600&fit=crop',
        name: 'wireless-ladegeraet',
        alt: 'Wireless Ladegerät'
      }
    ],
    attributes: [],
    default_attributes: [],
    variations: [],
    grouped_products: [],
    menu_order: 0
  },
  {
    id: 4,
    name: 'Designer T-Shirt Baumwolle',
    slug: 'designer-t-shirt-baumwolle',
    permalink: '/products/designer-t-shirt-baumwolle',
    date_created: '2024-01-15T13:00:00',
    date_modified: '2024-01-15T13:00:00',
    type: 'simple',
    status: 'publish',
    featured: true,
    catalog_visibility: 'visible',
    description: '<p>Hochwertiges T-Shirt aus 100% Bio-Baumwolle mit modernem Design. Nachhaltig produziert und angenehm zu tragen.</p>',
    short_description: 'Bio-Baumwoll T-Shirt mit modernem Design',
    sku: 'TSHIRT-COTTON-001',
    price: '24.99',
    regular_price: '24.99',
    sale_price: '',
    date_on_sale_from: null,
    date_on_sale_to: null,
    price_html: '<span class="price">24,99€</span>',
    on_sale: false,
    purchasable: true,
    total_sales: 234,
    virtual: false,
    downloadable: false,
    external_url: '',
    button_text: '',
    tax_status: 'taxable',
    tax_class: '',
    manage_stock: true,
    stock_quantity: 75,
    stock_status: 'instock',
    backorders: 'no',
    backorders_allowed: false,
    backordered: false,
    low_stock_amount: 15,
    sold_individually: false,
    weight: '0.15',
    dimensions: { length: '30', width: '25', height: '1' },
    shipping_required: true,
    shipping_taxable: true,
    shipping_class: '',
    shipping_class_id: 0,
    reviews_allowed: true,
    average_rating: '4.7',
    rating_count: 45,
    related_ids: [5],
    upsell_ids: [],
    cross_sell_ids: [],
    parent_id: 0,
    purchase_note: '',
    categories: [{ id: 2, name: 'Mode & Accessoires', slug: 'mode-accessoires' }],
    tags: [],
    images: [
      {
        id: 204,
        date_created: '2024-01-15T13:00:00',
        date_modified: '2024-01-15T13:00:00',
        src: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600&h=600&fit=crop',
        name: 'designer-t-shirt',
        alt: 'Designer T-Shirt Baumwolle'
      }
    ],
    attributes: [],
    default_attributes: [],
    variations: [],
    grouped_products: [],
    menu_order: 0
  },
  {
    id: 5,
    name: 'Vintage Sonnenbrille',
    slug: 'vintage-sonnenbrille',
    permalink: '/products/vintage-sonnenbrille',
    date_created: '2024-01-15T14:00:00',
    date_modified: '2024-01-15T14:00:00',
    type: 'simple',
    status: 'publish',
    featured: false,
    catalog_visibility: 'visible',
    description: '<p>Stilvolle Vintage-Sonnenbrille mit UV-400 Schutz. Klassisches Design trifft auf moderne Funktionalität.</p>',
    short_description: 'Stilvolle Vintage-Sonnenbrille mit UV-Schutz',
    sku: 'SUNGLASSES-VINTAGE-001',
    price: '49.99',
    regular_price: '59.99',
    sale_price: '49.99',
    date_on_sale_from: '2024-01-10T00:00:00',
    date_on_sale_to: '2024-02-28T23:59:59',
    price_html: '<span class="price"><del>59,99€</del> <ins>49,99€</ins></span>',
    on_sale: true,
    purchasable: true,
    total_sales: 67,
    virtual: false,
    downloadable: false,
    external_url: '',
    button_text: '',
    tax_status: 'taxable',
    tax_class: '',
    manage_stock: true,
    stock_quantity: 20,
    stock_status: 'instock',
    backorders: 'no',
    backorders_allowed: false,
    backordered: false,
    low_stock_amount: 5,
    sold_individually: false,
    weight: '0.05',
    dimensions: { length: '15', width: '14', height: '5' },
    shipping_required: true,
    shipping_taxable: true,
    shipping_class: '',
    shipping_class_id: 0,
    reviews_allowed: true,
    average_rating: '4.2',
    rating_count: 12,
    related_ids: [4],
    upsell_ids: [],
    cross_sell_ids: [],
    parent_id: 0,
    purchase_note: '',
    categories: [{ id: 2, name: 'Mode & Accessoires', slug: 'mode-accessoires' }],
    tags: [],
    images: [
      {
        id: 205,
        date_created: '2024-01-15T14:00:00',
        date_modified: '2024-01-15T14:00:00',
        src: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=600&h=600&fit=crop',
        name: 'vintage-sonnenbrille',
        alt: 'Vintage Sonnenbrille'
      }
    ],
    attributes: [],
    default_attributes: [],
    variations: [],
    grouped_products: [],
    menu_order: 0
  },
  {
    id: 6,
    name: 'Skandinavische Tischlampe',
    slug: 'skandinavische-tischlampe',
    permalink: '/products/skandinavische-tischlampe',
    date_created: '2024-01-15T15:00:00',
    date_modified: '2024-01-15T15:00:00',
    type: 'simple',
    status: 'publish',
    featured: false,
    catalog_visibility: 'visible',
    description: '<p>Minimalistische Tischlampe im skandinavischen Design aus nachhaltigen Materialien. Perfekt für Wohn- und Arbeitsbereich.</p>',
    short_description: 'Minimalistische Tischlampe aus nachhaltigen Materialien',
    sku: 'LAMP-SCANDI-001',
    price: '89.99',
    regular_price: '89.99',
    sale_price: '',
    date_on_sale_from: null,
    date_on_sale_to: null,
    price_html: '<span class="price">89,99€</span>',
    on_sale: false,
    purchasable: true,
    total_sales: 43,
    virtual: false,
    downloadable: false,
    external_url: '',
    button_text: '',
    tax_status: 'taxable',
    tax_class: '',
    manage_stock: true,
    stock_quantity: 12,
    stock_status: 'instock',
    backorders: 'no',
    backorders_allowed: false,
    backordered: false,
    low_stock_amount: 3,
    sold_individually: false,
    weight: '1.2',
    dimensions: { length: '25', width: '25', height: '45' },
    shipping_required: true,
    shipping_taxable: true,
    shipping_class: '',
    shipping_class_id: 0,
    reviews_allowed: true,
    average_rating: '4.8',
    rating_count: 19,
    related_ids: [],
    upsell_ids: [],
    cross_sell_ids: [],
    parent_id: 0,
    purchase_note: '',
    categories: [{ id: 3, name: 'Wohnen & Deko', slug: 'wohnen-deko' }],
    tags: [],
    images: [
      {
        id: 206,
        date_created: '2024-01-15T15:00:00',
        date_modified: '2024-01-15T15:00:00',
        src: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&h=600&fit=crop',
        name: 'skandinavische-tischlampe',
        alt: 'Skandinavische Tischlampe'
      }
    ],
    attributes: [],
    default_attributes: [],
    variations: [],
    grouped_products: [],
    menu_order: 0
  }
];